Repository wtbarnes/fiasco, pull requests merged in 2024-09, with the labels that each got.

#302 Fix bug reclvl file parser to account for ragged columns
  fiasco/io/sources/ion_sources.py
Labels: I/O, bugfix, Run v7 tests, backport 0.3

#303 Backport PR #302 on branch 0.3 (Fix bug reclvl file parser to account for ragged columns)
  fiasco/io/sources/ion_sources.py
Labels: I/O, bugfix, Run v7 tests, backport 0.3

#305 Fix docs build job in tox
  .github/workflows/ci.yml
  docs/conf.py
  docs/nitpick-exceptions
  tox.ini
Labels: backport 0.3

#306 Backport PR #305 on branch 0.3 (Fix docs build job in tox)
  .github/workflows/ci.yml
  docs/conf.py
  docs/nitpick-exceptions
  tox.ini
Labels: backport 0.3

#307 See if this helps with the doc version
  .readthedocs.yml
  .rtd-environment.yml
  docs/conf.py
  docs/index.rst
  pyproject.toml
Labels: backport 0.3

#309 Do not download and build database twice on RTD or GHA
  docs/conf.py
Labels: backport 0.3

#310 Backport PR #309 on branch 0.3 (Do not download and build database twice on RTD or GHA)
  docs/conf.py
Labels: backport 0.3

#311 Fix builds on tags
  .github/workflows/ci.yml
Labels: backport 0.3

#312 Backport PR #311 on branch 0.3 (Fix builds on tags)
  .github/workflows/ci.yml
Labels: backport 0.3

#313 Fix version rendering in docs
  docs/conf.py
  docs/index.rst
Labels: backport 0.3

#314 Backport PR #313 on branch 0.3 (Fix version rendering in docs)
  docs/conf.py
  docs/index.rst
Labels: backport 0.3

#293 Add new GauntFactor class and add Itoh integrated Gaunt factors to f-f radiative loss
  docs/references.bib
  fiasco/__init__.py
  fiasco/base.py
  fiasco/collections.py
  fiasco/conftest.py
  fiasco/gaunt.py
  fiasco/io/generic.py
  fiasco/io/sources/continuum_sources.py
  fiasco/io/sources/tests/test_sources.py
  fiasco/ions.py
  fiasco/tests/test_collections.py
  fiasco/tests/test_gaunt.py
  fiasco/tests/test_ion.py
  fiasco/util/data/file_hashes_v9.0.1.json
  fiasco/util/data/test_file_list.json
Labels: Run v9 tests
