Repository wtbarnes/fiasco, pull requests merged in 2025-07, with the labels that each got.

#388 Backport PR #368 on branch 0.4 (Bump OpenAstronomy/github-actions-workflows from 1 to 2)
  .github/workflows/ci.yml
Labels: dependencies, github_actions

#389 Supply default value for custom pytest commandline arguments when calling `getoption`
  fiasco/conftest.py
  fiasco/tests/idl/conftest.py
Labels: Run publish, Run full database tests, backport 0.4

#397 Fix title of IDL comparison G(T) plot
  examples/idl_comparisons/goft_comparison.py
Labels: docs, bugfix, backport 0.5

#399 Fix format in warning about out of date database
  fiasco/base.py
Labels: bugfix, backport 0.5

#400 Backport PR #399 on branch 0.5 (Fix format in warning about out of date database)
  fiasco/base.py
Labels: bugfix, backport 0.5
